Fix missing ProcessSingleton Mac symbols
Undefined symbols for architecture x86_64:
"ProcessSingleton::WaitForAndForwardOpenURLEvent(int)", referenced from:
ProcessSingleton::NotifyOtherProcessWithTimeout(base::CommandLine const&,
int, base::TimeDelta const&, bool) in process_singleton_posix.o
ld: symbol(s) not found for architecture x86_64

https://crrev.com/fe15df9c055b